"""UserDB name constraint set to unique

Revision ID: 87174d4cddb2
Revises: ef704c6c413c
Create Date: 2024-02-27 21:11:04.195343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87174d4cddb2'
down_revision = 'ef704c6c413c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_db_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_db', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_db_name'), type_='unique')

    # ### end Alembic commands ###
